In [1]:
import pandas as pd
import numpy as np

In [8]:
data=pd.read_csv(r"C:\Users\dell\Desktop\Srinivas\Assignments\Hypothesis\BuyerRatio.csv")

In [9]:
data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [6]:
import scipy.stats as stats

In [14]:
data.values

array([['Males', 50, 142, 131, 70],
       ['Females', 435, 1523, 1356, 750]], dtype=object)

In [15]:
data.index

RangeIndex(start=0, stop=2, step=1)

In [17]:
array=data.drop('Observed Values',axis=1)

In [18]:
array.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [20]:
df=np.array(array)

In [21]:
df.shape

(2, 4)

In [22]:
df.reshape(4,2)

array([[  50,  142],
       [ 131,   70],
       [ 435, 1523],
       [1356,  750]], dtype=int64)

In [26]:
data=pd.DataFrame(df.reshape(4,2),columns=['Male','Female'])

In [27]:
data

Male  Female
0    50     142
1   131      70
2   435    1523
3  1356     750

In [55]:
Observed_Values = data.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[  50  142]
 [ 131   70]
 [ 435 1523]
 [1356  750]]


In [56]:
val=stats.chi2_contingency(data)
val

(792.999178927871,
 1.4273789169473674e-171,
 3,
 array([[  84.95041508,  107.04958492],
        [  88.93246578,  112.06753422],
        [ 866.31725376, 1091.68274624],
        [ 931.79986538, 1174.20013462]]))

In [57]:
Expected_Values=val[3]

In [59]:
no_of_rows=len(data.iloc[0:2,0])
no_of_columns=len(data.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [60]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [61]:
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 792.9991789278708


In [62]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [63]:
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

p-value: 0.0
Significance level:  0.05
Degree of Freedom:  1
p-value: 0.0


In [64]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")
    
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Reject H0,There is a relationship between 2 categorical variables
Reject H0,There is a relationship between 2 categorical variables
